/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiConversationsConversationIdRouteImport } from './routes/api/conversations/$conversationId'
import { Route as ApiConversationsConversationIdMessagesRouteImport } from './routes/api/conversations/$conversationId.messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdRoute =
  ApiConversationsConversationIdRouteImport.update({
    id: '/api/conversations/$conversationId',
    path: '/api/conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsConversationIdMessagesRoute =
  ApiConversationsConversationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/conversations/$conversationId'
    | '/api/conversations/'
    | '/api/conversations/$conversationId/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/conversations/$conversationId'
    | '/api/conversations'
    | '/api/conversations/$conversationId/messages'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/conversations/$conversationId'
    | '/api/conversations/'
    | '/api/conversations/$conversationId/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiModelsRoute: typeof ApiModelsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiConversationsConversationIdRoute: typeof ApiConversationsConversationIdRouteWithChildren
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId': {
      id: '/api/conversations/$conversationId'
      path: '/api/conversations/$conversationId'
      fullPath: '/api/conversations/$conversationId'
      preLoaderRoute: typeof ApiConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId/messages': {
      id: '/api/conversations/$conversationId/messages'
      path: '/messages'
      fullPath: '/api/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
  }
}

interface ApiConversationsConversationIdRouteChildren {
  ApiConversationsConversationIdMessagesRoute: typeof ApiConversationsConversationIdMessagesRoute
}

const ApiConversationsConversationIdRouteChildren: ApiConversationsConversationIdRouteChildren =
  {
    ApiConversationsConversationIdMessagesRoute:
      ApiConversationsConversationIdMessagesRoute,
  }

const ApiConversationsConversationIdRouteWithChildren =
  ApiConversationsConversationIdRoute._addFileChildren(
    ApiConversationsConversationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiModelsRoute: ApiModelsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiConversationsConversationIdRoute:
    ApiConversationsConversationIdRouteWithChildren,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
